apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: mautic
  name: mautic 
  labels:
    app: mautic 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mautic 
  template:
    metadata:
      labels:
        app: mautic 
    spec:
      containers:
        - image: us.gcr.io/gigalixir-152404/mautic
          name: mautic
          env:
          - name: MAUTIC_RUN_CRON_JOBS
            value: "true"
          - name: MAUTIC_DB_HOST
            value: mysql:3306
          - name: MAUTIC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
          ports:
            - containerPort: 80
              name: mautic
          volumeMounts:
          - name: mautic-persistent-storage
            mountPath: /var/www/html
      volumes:
      - name: mautic-persistent-storage
        persistentVolumeClaim:
          claimName: mautic-pv-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mautic-pv-claim
  namespace: mautic
spec:
  # storageClassName: us-central-1a # see storage_class.yaml
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


